name: www.anthonysmith.me.uk
description: Ceci n'est pas un blog
url: http://www.anthonysmith.me.uk
exclude: [README.md, Gemfile, Gemfile.lock, CNAME]
permalink: /:year/:month/:day/:title/
paginate: 10
paginate_path: "page/:num/"
timezone: Europe/London
disqus_shortname: anthonysmithmeuk
twitter_username: anthonyjsmith