name: Anthony Smith
title: Anthony Smith # for jekyll-seo-tag, otherwise <title> ends up as <page title> | anthonyjsmith.github.io
description: 'Christian. Husband. CofE ordinand in Durham. Previous lives: organist, astronomer, software developer. Singer (classical).'
url: https://www.anthonysmith.me.uk
exclude: [README.md, Gemfile, Gemfile.lock, CNAME]
permalink: pretty
paginate: 100
paginate_path: "page/:num/"
timezone: Europe/London
disqus_shortname: anthonysmithmeuk
twitter:
  username: anthonyjsmith
author: anthonyjsmith

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"

# GitHub settings https://help.github.com/articles/configuring-jekyll/

# Configurable
github: [metadata]
kramdown:
  input: GFM
  hard_wrap: false
plugins:
  - jekyll-coffeescript
  - jekyll-paginate
  - jekyll-seo-tag # Added
  - jekyll-redirect-from # Added

# Settings that cannot be changed
lsi: false
# safe: true # <-- activating this seems to disable jekyll-paginate!
# source: [your repo's top level directory]
incremental: false
highlighter: rouge
gist:
  noscript: false
