name: Anthony Smith
description: Christian, C of E ordinand-in-waiting, freelance software gardener, married, astronomer, green, singer, organist, Wirral
url: http://www.anthonysmith.me.uk
exclude: [README.md, Gemfile, Gemfile.lock, CNAME]
permalink: pretty
paginate: 10
paginate_path: "page/:num/"
timezone: Europe/London
disqus_shortname: anthonysmithmeuk
twitter:
  username: anthonyjsmith
author: anthonyjsmith

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"

# GitHub settings https://help.github.com/articles/configuring-jekyll/

# Configurable
github: [metadata]
kramdown:
  input: GFM
  hard_wrap: false
gems:
  - jekyll-coffeescript
  - jekyll-paginate
  - jekyll-seo-tag

# Settings that cannot be changed
lsi: false
# safe: true # <-- activating this seems to disable jekyll-paginate!
# source: [your repo's top level directory]
incremental: false
highlighter: rouge
gist:
  noscript: false
